<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>hss</string>
	</array>
	<key>name</key>
	<string>HSS</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.event.hss</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\@(click|mouseover|mouseout)</string>
			<key>name</key>
			<string>event.hss</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.object.hss</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\@([A-Za-z0-9_]+)</string>
			<key>name</key>
			<string>object.hss</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#([A-Fa-f0-9]{1,6})</string>
			<key>name</key>
			<string>constant.color.hss</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([0-9]+)%?</string>
			<key>name</key>
			<string>constant.numeric.hss</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.instruction.hss</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.instruction.hss</string>
				</dict>
			</dict>
			<key>match</key>
			<string>#(new)\s([A-Za-z0-9_]+)</string>
			<key>name</key>
			<string>instruction.hss</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.hss</string>
	<key>uuid</key>
	<string>c83e74be-7081-4df8-bdf0-f0cb4db3b6f8</string>
</dict>
</plist>
